[package]
name = "rcommunity_core"
version = "0.0.1"
authors = ["Yu Yin <yxonic@gmail.com>"]
description = "Core utilities for crate `rcommunity`"
license = "MIT"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
thiserror = "1"

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
