[package]
name = "rcommunity_core"
version = "0.0.1"
authors = ["Yu Yin <yxonic@gmail.com>"]
description = "Core utilities for crate `rcommunity`"
license = "MIT"
edition = "2021"

[dependencies]
async-trait = "0.1.56"
thiserror = "1.0.31"

[dev-dependencies]
tokio = { version = "1.19.0", features = ["macros", "rt-multi-thread"] }
