[package]
name = "rcommunity_macros"
version = "0.0.2"
authors = ["Yu Yin <yxonic@gmail.com>"]
description = "Macros for `rcommunity`"
license = "MIT"
edition = "2021"

[lib]
proc_macro = true

[dependencies]
proc-macro2 = "1.0.43"
quote = "1.0.21"
syn = "1.0.99"
